name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Python dependencies
      run: pip3 install -r requirements.txt
    - name: Install Docker
      run: brew install docker docker-machine
    - name: Start Docker Machine
      run: brew services start docker-machine
    - name: Docker Machine default
      run: docker-machine create --driver virtualbox default
    - name: Run tests
      run: eval "$(docker-machine env default)" && python3 -m unittest discover -s macgrind/tests
