name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install homebrew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    - name: Install Docker CLI
      run: brew install docker
    - name: Install Docker Desktop
      run: brew cask install docker
    - name: Install Docker Machine
      run: brew install docker-machine 
    - name: Start Docker Machine
      run: brew services start docker-machine
    - name: Run Docker Desktop
      run: open /Applications/Docker.app
      # run: open /Applications/Docker.app && sleep 300 && docker run hello-world
    # - name: Wait for Docker Desktop to start
      # run: sleep 60
    # - name: Install Python dependencies
    #   run: pip3 install -r requirements.txt
    # - name: Run tests
    #   run: python3 -m unittest discover -s macgrind/tests
